[2023-03-29 01:19:58,631] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v2.process_data_task manual__2023-03-29T01:19:37.091527+00:00 [queued]>
[2023-03-29 01:19:58,682] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: SP_500_DATA_PIPELINE_v2.process_data_task manual__2023-03-29T01:19:37.091527+00:00 [queued]>
[2023-03-29 01:19:58,684] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 01:19:58,686] {taskinstance.py:1239} INFO - Starting attempt 1 of 3
[2023-03-29 01:19:58,687] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-03-29 01:19:58,738] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): process_data_task> on 2023-03-29 01:19:37.091527+00:00
[2023-03-29 01:19:58,749] {standard_task_runner.py:52} INFO - Started process 3483 to run task
[2023-03-29 01:19:58,769] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'SP_500_DATA_PIPELINE_v2', 'process_data_task', 'manual__2023-03-29T01:19:37.091527+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpbj1upu0z', '--error-file', '/tmp/tmp62w5hg0_']
[2023-03-29 01:19:58,773] {standard_task_runner.py:77} INFO - Job 53: Subtask process_data_task
[2023-03-29 01:19:59,175] {logging_mixin.py:109} INFO - Running <TaskInstance: SP_500_DATA_PIPELINE_v2.process_data_task manual__2023-03-29T01:19:37.091527+00:00 [running]> on host 67d8effe805a
[2023-03-29 01:19:59,491] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=SP_500_DATA_PIPELINE_v2
AIRFLOW_CTX_TASK_ID=process_data_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T01:19:37.091527+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T01:19:37.091527+00:00
[2023-03-29 01:21:34,869] {stock_data_transform.py:135} ERROR - An error occurred during transformation: Recursive view `stock_data` detected (cycle: `stock_data` -> `stock_data`)
[2023-03-29 01:21:34,877] {python.py:175} INFO - Done. Returned value was: None
[2023-03-29 01:21:34,964] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=SP_500_DATA_PIPELINE_v2, task_id=process_data_task, execution_date=20230329T011937, start_date=20230329T011958, end_date=20230329T012134
[2023-03-29 01:21:35,092] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-29 01:21:35,228] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
